import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopBar from '@/components/topbar/TopBar'
import Navbar from '@/components/navbar/Navbar'
import QueryProvider from "@/context/QueryProvider"
import i18nConfig from '@/next-i18next.config';
import { ApiCacheProvider } from '@/context/CacheContextApi'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Softenger Test',
  description: 'Generated by create next app',
}

export async function generateStaticParams() {
  return i18nConfig.locales.map(locale => ({ locale }));
}

export default function RootLayout({
  children, params
}: {
  children: React.ReactNode,
  params: { locale: string }
}) {
  return (
    <html lang={params.locale}>
      <body className={inter.className}>
        <TopBar locale={params.locale} />
        <ApiCacheProvider>
          <QueryProvider>
            <Navbar locale={params.locale} />
            {children}
          </QueryProvider>
        </ApiCacheProvider>
      </body>
    </html>
  )
}


